Update run.py to fix missing import (#850)
Adding "import signal" to resolve the error:
```
Traceback (most recent call last):
  File "awsome-distributed-training/3.test_cases/megatron/nemo/slurm/run.py", line 150, in <module>
    plugins.PreemptionPlugin(callbacks=[run.Config(PreemptionCallback, sig=signal.SIGINT)]),
NameError: name 'signal' is not defined
```