update: 3.test_cases/1.megatron-lm
- update base image to latest image version: nvcr.io/nvidia/pytorch:23.09-py3
- update EFA installer to latest version: 1.28.0
- update aws_ofi_nccl to latest version: 1.7.3-aws

Fixes:
- do not cleanup all hpcx libraries, otherwise torch complais like this:
python -c 'import torch'
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 234, in <module>
    from torch._C import *  # noqa: F403
ImportError: libucm.so.0: cannot open shared object file: No such file or directory

In fact we do not have to remove all hpcx libraries, we just need to remove openmp to avoid
conflict with /opt/amazon/ompi

- remove NCCL library update hank since nvcr.io/nvidia/pytorch:23.09-py3 already has latest NCCL
- EFA: add --no-verify to installation script, otherwise  build fails on instances with EFAs
- install libhwloc-dev, required for aws_ofi_nccl plugin

Signed-off-by: Dmitry Monakhov <monakhov@amazon.com>