Update gen-keypair-ubuntu.sh to update authorized_keys
IHAC who accidentally remove `authorized_keys` after cluster setup. That caused
```
2024-12-26T09:09:03.929Z
Generate a new keypair...
2024-12-26T09:09:04.180Z
+ ssh-keygen -t rsa -q -f id_rsa -N ‘’
2024-12-26T09:09:04.180Z
id_rsa already exists.
2024-12-26T09:09:04.430Z
Overwrite (y/n)? Traceback (most recent call last): File “lifecycle_script.py”, line 232, in <module> main(args) File “lifecycle_script.py”, line 185, in main ExecuteBashScript(“./utils/gen-keypair-ubuntu.sh”).run() File “lifecycle_script.py”, line 31, in run result.check_returncode() File “/usr/lib/python3.8/subprocess.py”, line 448, in check_returncode raise CalledProcessError(self.returncode, self.args, self.stdout,
2024-12-26T09:09:08.979Z
subprocess.CalledProcessError: Command ’[’sudo’, ‘bash’, ‘./utils/gen-keypair-ubuntu.sh’]' returned non-zero
```
when they tried to add a new node as `GENERATE_KEYPAIR=1` when we don't have the contents of `id_rsa.pub` in `authorized_keys`, even when the key pair does exist.